### ISSUE TITLE
Scrubbing confidential data

### ISSUE THREAD

**Issue by alexellis** [kanisterio/kanister#123]
This project looks very promising - I came across it while reviewing KubeCon CfPs. I had a few initial questions for you?

* How are you performing scrubbing of confidential data such as payment information?
* What DB back-ends are supported and what is in the roadmap for the future?
* Do DB backups have to be stored on S3 or are other back-ends supported?

Cheers,

Alex

**Comment by tdmanv** [comment]
Hi Alex, thank you for the questions.

- Data masking/scrubbing is an important feature that we've been considering for a while. It's a good use case for Kanister because it requires data-service specific commands to manipulate/transform data. We don't have have any examples for that at this time.
- Kanister releases include example helm charts for 4 popular open source DBs: MySQL, MongoDB, , PostgreSQL. We've also just adding ElasticSearch and are doing some doc updates. See https://docs.kanister.io/helm.html
- We've found that most object stores supports the S3 protocol so although the current examples use the S3 protocol, AWS S3 is not required.
- We don't publish a formal roadmap, but the next large feature we're considering 

If you have requirements for data-scrubbing, specific DBs, or backup targets, please do let us know! We love hearing about use cases. Our slack workspace is the best way to start a conversation: https://kasten.typeform.com/to/QBcw8T

Thanks,
Tom

**Comment by tdmanv** [comment]
Another thing - our intern, @gauthamsunjay also added a library to support GCS and Azure object stores using their native protocols. We don't consume that library yet, but that is also in the works.

**Comment by julio-lopez** [comment]
Questions have been answered.
