### ISSUE TITLE
etcd-incluster-blueprint.yaml Requires tar

### ISSUE THREAD

**Issue by B1ue-W01f** [kanisterio/kanister#1839]
[etcd-incluster-blueprint.yaml](https://github.com/kanisterio/kanister/blob/master/examples/etcd/etcd-in-cluster/k8s/etcd-incluster-blueprint.yaml)

The above blueprint requires `tar` to be present on the forward container to use the `kubectl cp` command, this does not appear to be present for one or both of an ETCD container image or the ghcr.io/kanisterio/kanister-kubectl-1.18:0.85.0 image used.

Nothing special about the ETCD in use so I'd presume an alternative solution was needed. Or at minimum inclusion in documentation.

Edit: annoyingly `cat` doesnt appear to be available within the etcd container image either.

**Comment by viveksinghggits** [comment]
@shahpratikr can you please look into this please?

**Comment by shahpratikr** [comment]
I have tried following solutions without any luck.
- tried to install `tar` in `kanister/kubectl` image. but since `kubectl cp` expects tar on etcd pod, this solution didn't work
- tried to combine commands from phases into one in hope of we don't need to run `kubectl cp` but since we run `snapshot save` inside etcd pod, eventually we will need to run copy command
- tried to install `etcdctl` on `kanister/kubectl` image pod, it failed with `certs not found` error and without cert options, execution fails with `context timeout issue`
I am not sure what else I can try here to fix this.

**Comment by B1ue-W01f** [comment]
@shahpratikr @viveksinghggits If this is not possible to resolve, I'd suggest removing it from the examples, or at least caveat it - fundamentally it is none functional as is and only likely to lead to confusion.

**Comment by viveksinghggits** [comment]
Hi @B1ue-W01f 
The default behavior that is documented here doesn't seem to be working like you have pointed out. 
We were exploring the other options and it's our bad that we didn't properly update the progress here.
We will update the progress here soon.
