### ISSUE TITLE
use an aws role arn (irsa) while still loading the webIdenityToken from a file

### ISSUE THREAD

**Issue by clayrisser** [kanisterio/kanister#2509]
When configuring an application with IAM roles for service accounts (IRSA) in a Kubernetes environment, you should not need to manually supply the Web Identity Token in your configuration. This token is dynamically generated and injected into your pod by the EKS environment.

The token should be loaded from a file.

https://github.com/kanisterio/kanister/blob/master/pkg/aws/aws.go#L132

I see that there is an option to load the webIdenityToken from a file, but that only works when configured using ENVs.

https://github.com/kanisterio/kanister/blob/master/pkg/aws/aws.go#L105

It should be possible to use an aws role arn (irsa) while still loading the webIdenityToken from a file.

My proposed solution is that instead of returning `nil, nil` when a webIdenityToken is not found, simply check to see if it's located at `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` first.

https://github.com/kanisterio/kanister/blob/master/pkg/aws/aws.go#L126

**Comment by clayrisser** [comment]
In addition I think it would need to add the `eks.amazonaws.com/role-arn` annotation to the job.

**Comment by viveksinghggits** [comment]
cc @hairyhum

**Comment by leuyentran** [comment]
hi @clayrisser , I think I need your help to understand better the scenario being described here 😄 

My question is whether or not the description below is the same set up that you are using? If not maybe we are missing a third use case! 

_TL,DR: checking for `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` is done via env var `AWS_WEB_IDENTITY_TOKEN_FILE` if IRSA and Amazon EKS Pod Identity Webhook are [set up](https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html)_

Long explantion:

> When configuring an application with IAM roles for service accounts (IRSA) in a Kubernetes environment, you should not need to manually supply the Web Identity Token in your configuration. This token is dynamically generated and injected into your pod by the EKS environment.
> 
> The token should be loaded from a file.
> 
> https://github.com/kanisterio/kanister/blob/master/pkg/aws/aws.go#L132

You are absolutely right that when IRSA is used, there shouldn't be a need to manually supply for Web Identity Token because the token should be requested and stored by the `kubelet` on behalf of the Pod ([src](https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html#:~:text=The%20kubelet%20requests%20and%20stores%20the%20token%20on%20behalf%20of%20the%20Pod.)). 

Additionally, if running on EKS clusters, the Amazon EKS Pod Identity Webhook watches for Pod that uses K8s Service Account annotated with `eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role` and [injects several ENV_VAR into POD](https://github.com/aws/amazon-eks-pod-identity-webhook?tab=readme-ov-file#eks-walkthrough), including : 
-`AWS_WEB_IDENTITY_TOKEN_FILE` that points to where the token file should be store, i.e. `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`
-`AWS_ROLE_ARN` which is the AWS role that should be assumed. This is the same role that the K8s Service Account is annotated via`eks.amazonaws.com/role-arn` 

The scenario with Amazon EKS Pod Identity Webhook above is what the function [fetchWebIdentityTokenFromFile](https://github.com/kanisterio/kanister/blob/a3656cd31f0dd601510c1c6247b89d528a89598b/pkg/aws/aws.go#L142C5-L142C5) accounts for. (Albeit that is actually not the best function name 😅 )

Which means the statement below is true, however the environment variables configuration part should be done by Amazon EKS Pod Identity Webhook on behalf of the Pod, and there should not be any additional work from user beside setting up (step 1, 2, and 3 [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)) 
 > I see that there is an option to load the webIdenityToken from a file, but that only works when configured using ENVs.

Going back to the bugfix suggestion: 
> It should be possible to use an aws role arn (irsa) while still loading the webIdenityToken from a file.

This is entirely the intention of the caller function [authenticateAWSCredentials](https://github.com/kanisterio/kanister/blob/a3656cd31f0dd601510c1c6247b89d528a89598b/pkg/aws/aws.go#L85C6-L85C32) 

> My proposed solution is that instead of returning nil, nil when a webIdenityToken is not found, simply check to see if it's located at /var/run/secrets/eks.amazonaws.com/serviceaccount/token first.

And checking for a token located at `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` should be achieved with [fetchWebIdentityTokenFromFile](https://github.com/kanisterio/kanister/blob/a3656cd31f0dd601510c1c6247b89d528a89598b/pkg/aws/aws.go#L142C5-L142C5) if the cluster and Pod are set up to use ISRA and Amazon EKS Pod Identity Webhook

**Comment by clayrisser** [comment]
Ok, so it works with irsa? Do you have any examples?

**Comment by hairyhum** [comment]
@clayrisser there are no examples to demonstrate this specific behaviour, but what you can do is to create a [KubeTask](https://docs.kanister.io/functions.html#kubetask) function in your blueprint and specify `podOverride` there to contain `serviceAccountName` that you need:

```
- func: KubeTask
  name: examplePhase
  args:
    namespace: "{{ .Deployment.Namespace }}"
    image: busybox
    podOverride:
      serviceAccountName: my-serviceaccount
    command:
      - sh
      - -c
      - |
        aws sts get-caller-identity
```

If the pod is created in EKS and credentials injection is properly set up, you should get the role for the service account you're requesting.
