### ISSUE TITLE
client side encryption and pke

### ISSUE THREAD

**Issue by tcurdt** [kanisterio/kanister#2916]
**Is your feature request related to a problem? Please describe.**

Maybe I am just not finding the documentation?
It seems like e.g. the postgres blueprint uses kopia and therefor should support encryption.

But I could not find any more details on that.
Which secret does it use to encrypt?

**Describe the solution you'd like**

While this flow looks nice https://github.com/kanisterio/kanister/tree/master/examples/postgresql it would be great to to also mention the encryption angle.

And I would prefer a blueprint that supports pke even more.

Now pke would be probably more a feature request for kopia, but even to support that flow in a different blueprint it seems like something is missing.

The command `kanctl create actionset --action backup --namespace kanister --blueprint postgres-bp --statefulset postgres-test/my-release-postgresql --profile postgres-test/s3-profile-7d6wt` would need to get the public key for the encryption from a secret. That's fine.

But the command `kanctl --namespace kanister create actionset --action restore --from backup-glptq` would need to ask for the private key to restore the backup. Sharing the private key via secrets could be an option but is not ideal. It would be better if it was kept ephemeral.

So the question is: How can one pass ephemeral and sensitive data via `kanctl` to a blueprint?

Does this question make sense?

**Comment by michaelcourcy** [comment]
Hi @tcurdt 

Unfortunately the blueprint using kopia are only working in the context of Kasten By Veeam. You're 100% right when you mention the encryption angle, because in this case it is kasten that provide the context that let `kando` operate with an encryption key. So the blueprint https://github.com/kanisterio/kanister/blob/master/examples/postgresql/postgres-blueprint.yaml can be used in kanister standalone but the blueprint https://github.com/kanisterio/kanister/blob/master/examples/postgresql/blueprint-v2/postgres-blueprint.yaml can only be used in kasten+kanister context.

Michael

**Comment by michaelcourcy** [comment]
I must add that works to make them available in standalone mode is still under development. But it's hard at this point to know when that will be available.

**Comment by hairyhum** [comment]
Closing since the question was answered.
